name: Sync to personal repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Config git extraheader
        run: |
          git config --unset-all http.https://github.com/.extraheader

      - name: Push to release repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: .
          destination-github-username: 'HiimKwak'
          destination-repository-name: 'hufchichi_client'
