name: Sync to personal repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pushes to personal repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.KWAK_GITHUB_TOKEN }}
        repository: HiimKwak/hufstreaming_client
        branch: main
